### ISSUE TITLE
Wrong MOS value of 4.5 when high latency

### ISSUE THREAD

**Issue by oanguenot** [ggarber/rtcscore#3]
Testing the algorithm with:
- packetLoss: 8%
- RTT: 1000
Return a MOS value of 4.5 instead of 1

**Comment by oanguenot** [comment]
I have a fix in a derived branch from "develop" locally but I can't push my commit (tests + code).

**Comment by oanguenot** [comment]
I changed line 
`const Id = delay * 0.03 + (delay > 150 ? 0.1 * delay - 150 : 0);`
to 
`const Id = delay * 0.03 + (delay > 150 ? 0.1 * (delay - 150) : 0);`

**Comment by ggarber** [comment]
You are totally right.   Merged the fix.  Thank you very much @oanguenot !
